package crud

const pathEntityCreateAjax = "entity-create-ajax"
const pathEntityManager = "entity-manager"
const pathEntityRead = "entity-read"
const pathEntityUpdate = "entity-update"
const pathEntityUpdateAjax = "entity-update-ajax"
const pathEntityTrashAjax = "entity-trash-ajax"

const FORM_FIELD_TYPE_NUMBER = "number"
const FORM_FIELD_TYPE_STRING = "string"
const FORM_FIELD_TYPE_TEXTAREA = "textarea"
const FORM_FIELD_TYPE_SELECT = "select"
const FORM_FIELD_TYPE_IMAGE = "image"
const FORM_FIELD_TYPE_IMAGE_INLINE = "image_inline"
const FORM_FIELD_TYPE_HTMLAREA = "htmlarea"
const FORM_FIELD_TYPE_BLOCKAREA = "blockarea"
const FORM_FIELD_TYPE_DATETIME = "datetime"
const FORM_FIELD_TYPE_PASSWORD = "password"
const FORM_FIELD_TYPE_RAW = "raw"
